# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0003_auto_20160404_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='result',
            field=models.IntegerField(blank=True, choices=[(2, 'fail'), (1, 'success'), (0, 'unknown')]),
        ),
    ]
