# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0004_auto_20160404_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_image', to='image_collector.Image'),
        ),
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_post', to='image_collector.Post'),
        ),
        migrations.AlterField(
            model_name='log',
            name='result',
            field=models.IntegerField(choices=[(2, 'fail'), (1, 'success'), (0, 'unknown')]),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_user', to='image_collector.ImageUser'),
        ),
        migrations.AlterField(
            model_name='log',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_website', to='image_collector.Website'),
        ),
    ]
