# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0005_auto_20160404_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='video',
        ),
        migrations.AddField(
            model_name='mimetype',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
