# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0006_auto_20160404_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='credential',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='credential',
            name='client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='credential',
            name='pin_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='credential',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='credential',
            name='short_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='credential',
            name='api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='credential',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
