# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0007_auto_20160405_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
