# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0009_auto_20160405_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='post',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
