# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0010_auto_20160406_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
