# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0011_remove_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='short_name',
            new_name='credential_key',
        ),
        migrations.RemoveField(
            model_name='imageuser',
            name='website',
        ),
    ]
