# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0012_auto_20160409_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
