# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0016_image_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('jsonData', jsonfield.fields.JSONField()),
            ],
        ),
    ]
