# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0018_auto_20160411_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='etag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
