# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0019_post_etag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='etag',
            field=models.CharField(blank=True, default={'hello': 'Hi there!'}, max_length=255),
        ),
    ]
