# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0020_auto_20160411_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='etag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='storage',
            name='jsonData',
            field=jsonfield.fields.JSONField(default={'hello': 'Hi there!'}),
        ),
    ]
