# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 02:08
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0021_auto_20160411_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='jsonData',
            field=jsonfield.fields.JSONField(default={'hello': 'Hi there!', 'help': "Put some valid JSON in here and you'll do fine!", 'information': 'This is here for you to use as your storage of information if need be'}),
        ),
    ]
