# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0022_auto_20160411_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
