# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 23:03
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0025_auto_20160419_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='jsonData',
            field=jsonfield.fields.JSONField(default='{"users": ["bsquidwrd"]}'),
        ),
    ]
