# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 05:46
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0027_auto_20160502_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='jsonData',
            field=jsonfield.fields.JSONField(default={'users': ['bsquidwrd']}),
        ),
    ]
