# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0028_auto_20160509_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
